model:
  name: ldm
  base_learning_rate: 1.0e-06
  scale_lr: false
  target: models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: class_label
    image_size: 32
    channels: 4
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    unet_config:
      target: modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 256
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
    
    first_stage_config:
      name: vqgan
      target: models.autoencoder.VQModelInterface
      params:
        embed_dim: 4
        n_embed: 16384
        ckpt_path: /some/pretrained/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 32
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: modules.encoders.modules.ClassEmbedder
      params:
        n_classes: 9
        embed_dim: 512
        key: class_label
    
data:
  dataset_name: wikiart
  target: dataloader.datamodule.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 12
    wrap: false
    train:
      target: dataloader.custom.WikiartImageDatasetTrain
      params:
        training_images_list_file: /some/train.txt
        train_labels_file: /some/train_labels.txt
        size: 256
    validation:
      target: dataloader.custom.WikiartImageDatasetTest
      params:
        test_images_list_file: /some/test.txt
        test_labels_file: /some/test_labels.txt
        size: 256

lightning:
  callbacks:
    image_logger:
      target: dataloader.datamodule.ImageLogger
      params:
        batch_frequency: 1
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    n_gpus: 2
    n_epochs: 1